name: Build Android APK

on:
  # This lets you run the build manually from the "Actions" tab
  workflow_dispatch:

  # This runs the build automatically every time you push to the "master" branch
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the correct Java version for Android (Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Gradle dependencies to speed up future builds
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Give the gradlew script permission to run (a common gotcha!)
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # 5. This is the main build command
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        
      # 6. This saves the built APK so you can download it
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: androidnsfilter-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
